### ISSUE TITLE
`videos?part=mostReplayed&id={videoId}` returns `HTTP ERROR 500` on video not having most replayed data

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/YouTube-operational-API#128]
> Hey I'm not sure it's linked to the api but I get an issue when requesting "http://localhost/YouTube-operational-API/videos?part=mostReplayed&id={videoId}" : it says "HTTP ERROR 500" (but other requests seem to work well). Any idea why this happens and how to fix it ?

_Originally posted by @Awksys in #11_

**Comment by Benjamin-Loison** [comment]
@Awksys instead of commenting, please post an issue, as your issue doesn't seem related to the issue you commented on.

For better helping you, please provide PHP logs (`C:\wamp64\logs\php_error.log` as you're using WampServer) corresponding to your HTTP failed request.

**Comment by Awksys** [comment]
Ok thanks @Benjamin-Loison (I'm new to github and I don't know much about how everything's working here...).
The error logged is:
"[27-Jan-2023 18:27:18 UTC] PHP Fatal error:  Uncaught TypeError: end(): Argument #1 ($array) must be of type array, null given in C:\wamp64\www\YouTube-operational-API\videos.php:245
Stack trace:
#0 C:\wamp64\www\YouTube-operational-API\videos.php(245): end(NULL)
#1 C:\wamp64\www\YouTube-operational-API\videos.php(325): getItem('yLqTBlJ3cSg')
#2 C:\wamp64\www\YouTube-operational-API\videos.php(48): getAPI(Array)
#3 {main}
  thrown in C:\wamp64\www\YouTube-operational-API\videos.php on line 245"

**Comment by Benjamin-Loison** [comment]
As precised in #29, I don't guarantee any response when requesting content that doesn't exist. It's the case here [`yLqTBlJ3cSg`](https://www.youtube.com/watch?v=yLqTBlJ3cSg) doesn't have most replayed data.

**Comment by Awksys** [comment]
My bad yes... Most replayed parts of the video aren't showing up on youtube that's why it doesn't output anything. I think we can close this issue as this isn't one.

**Comment by Benjamin-Loison** [comment]
I fixed the issue anyway, the API now returns:

```json
{
    "kind": "youtube#videoListResponse",
    "etag": "NotImplemented",
    "items": [
        {
            "kind": "youtube#video",
            "etag": "NotImplemented",
            "id": "yLqTBlJ3cSg",
            "mostReplayed": null
        }
    ]
}
```
Source: https://yt.lemnoslife.com/videos?part=mostReplayed&id=yLqTBlJ3cSg

**Comment by Awksys** [comment]
Is it easy to apply this on my own instance of the api ? I updated the api files but it still doesn't display the `"mostReplayed": null`.

**Comment by Benjamin-Loison** [comment]
@Awksys If you modified `videos.php`, as in 6e38f7b6178f6c15455d7502d98a7a1d31637498, then you proceeded incorrectly I guess. If you have `git clone` the repository and not downloaded the `zip`, then it's as easy as doing `git pull`. Otherwise provide the `if ($options['mostReplayed'])` code block you have and associated PHP logs.
